# Generated by Django 4.0.4 on 2022-06-03 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='country',
            field=models.CharField(blank=True, choices=[('인도', '인도'), ('인도네시아', '인도네시아'), ('일본', '일본'), ('스페인', '스페인'), ('브라질', '브라질'), ('중국', '중국')], max_length=10, null=True, verbose_name='나라'),
        ),
        migrations.AlterField(
            model_name='post',
            name='greetings',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='인삿말'),
        ),
        migrations.AlterField(
            model_name='post',
            name='nickname',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='닉네임'),
        ),
    ]
