# Generated by Django 4.0.4 on 2022-06-03 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_post_country_alter_post_greetings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='이미지'),
        ),
        migrations.AlterField(
            model_name='post',
            name='nickname',
            field=models.CharField(max_length=10, null=True, verbose_name='닉네임'),
        ),
    ]
