# Generated by Django 4.0.4 on 2022-06-03 21:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0004_alter_post_nickname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, choices=[('인도', '인도'), ('인도네시아', '인도네시아'), ('일본', '일본'), ('스페인', '스페인'), ('브라질', '브라질'), ('중국', '중국')], max_length=10, null=True, verbose_name='나라')),
                ('nickname', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='닉네임')),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Country',
                'db_table': 'Country',
            },
        ),
        migrations.CreateModel(
            name='Greetings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('greetings', models.CharField(blank=True, max_length=40, null=True, verbose_name='인삿말')),
                ('nickname', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='닉네임')),
            ],
            options={
                'verbose_name': 'Greetings',
                'verbose_name_plural': 'Greetings',
                'db_table': 'Greetings',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='이미지')),
                ('nickname', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='닉네임')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Image',
                'db_table': 'Image',
            },
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
